### ISSUE TITLE
Build Failure in Tests

### ISSUE THREAD

**Issue by luator** [filtering-library/fl#4]
The tests are currently failing due to build issues in the test files.

## How to reproduce
1) Create a catkin workspace with fl in it
3) `catkin run_tests fl`

## Expected behaviour
Build and execution of all tests succeeds.

## Actual behaviour
Build of tests fails with several errors.  First error is:
```
In file included from fl/test/gaussian_filter/kalman_filter_test.cpp:25:0:
fl/src/fl/test/gaussian_filter/gaussian_filter_test_suite.hpp:87:17: error: wrong number of template arguments (2, should be 3)
                 > LinearTransition;
                 ^
```

**Comment by luator** [comment]
@mwuethri Can you take a look at this?

**Comment by wumanu** [comment]
i will have a look next week

**Comment by wumanu** [comment]
fixed some tests and disabled some that were outdated

**Comment by luator** [comment]
@mwuethri Thanks for the fixes. There are still a few tests failing for me, though:
![2019-12-18 09 44 12  0715baa2b3af](https://user-images.githubusercontent.com/9333121/71070433-0eba3600-217b-11ea-8689-0f5a27b10bb2.jpg)
